### ISSUE TITLE
feature new video on PLI

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#118]
Add a news card (and video at community gallery?)

3D Polarized Light Imaging - Towards a 3D fiber atlas of the brain
 https://fz-juelich.sciebo.de/s/ChEj4cYMiYNXKfx
https://www.youtube.com/watch?v=PTOQFo1GJaI

Revealing the entire human brains’ nerve fiber architecture at the axonal level poses immense technological and computational challenges. At the Jülich Institute of Neuroscience and Medicine, Structural and functional organisation of the brain (INM-1), we are developing the neuro-microscopy technique 3D Polarized Light Imaging (3D-PLI) to address these challenges and push the methods towards high-throughput, large-scale analysis of brain connectivity and 3D Fiber atlas generation. The movie is meant to introduce the fundamental ingredients of 3D-PLI, including brain sectioning, imaging principles, supercomputing usage and data visualisation.

**Comment by 3design** [comment]
Is there a way to reduce the text to 2 sentences?

**Comment by SusanneWenzel** [comment]
For the card the heading would be sufficient. The text is just C&P from the current youtube location and could be used again for the description at the BigBrainProject channel again.

If you'd like to have sth more on the card I propose:
An entertaining introduction into the fundamental ingredients of 3D-PLI, including brain sectioning, imaging principles, supercomputing usage and data visualisation.

**Comment by 3design** [comment]
Upload video to bbp youtube page and copy the details from the fzj youtube description

**Comment by 3design** [comment]
https://youtu.be/mu3ePKbH_5k
