### ISSUE TITLE
New HIBALL members

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#119]
Please add new members to the team list
Lina Schaare
Bin Wan 
Seyma Bayrak 
Meike Hettwer

Metadata: https://drive.google.com/file/d/1yI7cyAvo-IvpBlGreRuWeb8cEaxquYbf/view?usp=sharing
I already asked for images, will put them in the according google folder

**Comment by 3design** [comment]
page updated. Waiting for photos

**Comment by SusanneWenzel** [comment]
thanks. 
- Meike Hettwer is INM-7, please correct
- the MPG people are from
Otto Hahn Group Cognitive Neurogenetics
Max Planck Institute for Human Cognitive and Brain Sciences
please correct
I updated the "master table"

**Comment by SusanneWenzel** [comment]
added image of Bin Wan to /BigBrainProject_Webpage/images_videos/HIBALLpeople

**Comment by SusanneWenzel** [comment]
Image Lina Schaare added to the google folder.
@3design please also note the comment above

**Comment by 3design** [comment]
could not find image of lina in /BigBrainProject_Webpage/images_videos/HIBALLpeople

**Comment by SusanneWenzel** [comment]
@3design sorry, my fault, I forgot to move it to the correct place. It's there now
