### ISSUE TITLE
Add: Talk by Blake Richards at July 6 as News at landing page

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#12]
Jülicher Kolloquium with Blake Richards 
date July 6 2020
HIBALL and Helmholtz AI Local at Forschungszentrum Jülich invite to an online-talk by
Blake Richards
Predictive cost functions in the neocortex
link: http://indico-jsc.fz-juelich.de/e/JuelichKolloquium_BlakeRichards

**Comment by 3design** [comment]
add video link
