### ISSUE TITLE
New video available

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#124]
Tutorial by Timo Dickscheid
The multilevel human brain atlas in EBRAINS
https://www.youtube.com/watch?v=SZ1GgExT3Zk&t=1407s

Shall we add it to the community videos?

@pjtoussaint @3design 
Or shall we open the teaching side and collect all the teaching videos there? I.E. also link the winter School videos again

**Comment by 3design** [comment]
Added to community page. Will wait for decision re: teaching resources
