### ISSUE TITLE
Inform about FTP issue

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#125]
Maps & Models: Please add information how to configure browser regarding ftp 
Accordingly add a news card at the landing page
Information can be taken from https://bigbrain-forum.loris.ca/t/access-to-the-bigbrain-projects-ftp-site-from-a-browser/374

**Comment by 3design** [comment]
@SusanneWenzel the new https://ftp.bigbrainproject.org/ url fixes the issue of browser compatibility I believe. Should I still put a link to this browser fix article?

**Comment by SusanneWenzel** [comment]
We never know how people access the data. Better provide the information
