### ISSUE TITLE
New HIBALL member

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#127]
Please add Kai Kiwitz to the HIBALL Team 
Image in the folder

Kai Kiwitz <https://www.researchgate.net/profile/Kai-Kiwitz>
Cécile and Oskar Vogt Institute of Brain Research <https://www.uniklinik-duesseldorf.de/en/cecile-and-oskar-vogt-institute-of-brain-research>
Heinrich Heine University Düsseldorf

**Comment by 3design** [comment]
@SusanneWenzel Will Cecile and Oskar Vogt share a single image on the page, or will they have their own images?

**Comment by SusanneWenzel** [comment]
??? It is just Kai. 
'Cécile and Oskar Vogt Institute of Brain Research' is the name of the institute in Düsseldorf ^^

**Comment by 3design** [comment]
@SusanneWenzel oh I see... I thought this was multiple entries haha! thanks for answering :D
