### ISSUE TITLE
add some credits to the Konrad Video

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#128]
Please add credits for the music and an image I used to the description of the youtube video

Music by Wavecont, https://www.wavecont.com/free-download/
Licensed under creative commons Attribution-ShareAlike 4.0 International
https://creativecommons.org/licenses/by-sa/4.0/
Music promoted by https://www.chosic.com/ 

Background Image by Gordon Johnson 
https://pixabay.com/de/vectors/gehirn-ai-k%C3%BCnstliche-intelligenz-4863428/

**Comment by 3design** [comment]
Done 

https://youtu.be/0dCwWqK5-Do

**Comment by 3design** [comment]
Leave this task open until new video is uploaded
