### ISSUE TITLE
Add: Dissertations at publications

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#13]
Hannah Spitzer 2019, Automated parcellation of cytoarchitectonic cortical regions using supervised machine learning
link: tdb

Miriam Menzel 2018, Finite-difference time-domain simulations assisting to reconstruct the brain's nerve fiber architecture by 3D polarized light imaging
http://publications.rwth-aachen.de/record/750948

Giuseppe Tabbì 2016,  Parallelization of a Data-Driven Independent Component Analysis to Analyze Large 3D-Polarized Light Imaging Data Sets 
http://elpub.bib.uni-wuppertal.de/servlets/DocumentServlet?id=6010

Hendrik Wiese 2016, Enhancing the Signal Interpretation and Microscopical Hardware Concept of 3D Polarized Light Imaging 
http://elpub.bib.uni-wuppertal.de/servlets/DocumentServlet?id=6760

Julia Reckfort 2015, New Approaches to the Interpretation of 3D-Polarized Light Imaging Signals for an Advanced Extraction of Fiber Orientation 
http://elpub.bib.uni-wuppertal.de/servlets/DocumentServlet?id=5100&lang=en

Melanie Dohmen 2013, Towards the Reconstruction of Fiber Tracts in the Human Brain by Means of 3D Polarized Light Imaging  
http://elpub.bib.uni-wuppertal.de/servlets/DocumentServlet?id=3793

**Comment by pjtoussaint** [comment]
The section must be called "Dissertations".
