### ISSUE TITLE
New Featured Paper Article

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#132]
I put material for a Featured Paper article about Christian's NeuroImage Paper at BigBrainProject Google Drive at /Website/FeaturedSeries 
There is just one folder currently.
It is kind of a blog post. The text is given in text.docx. Image and video are given in the folder, too.

Where should we collect such material in future? We have the featured scholar video under videos. I put this blog post material under website. Shall we consolidate that?

**Comment by SusanneWenzel** [comment]
wasn't that a bit early? it is not yet released :)

**Comment by 3design** [comment]
Ooops! I got too excited :D
