### ISSUE TITLE
Change: Maps&Models nehuba links to specific maps

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#15]
1. please open in new tab
2. cortical layer maps: https://interactive-viewer.apps.hbp.eu/?templateSelected=Big+Brain+%28Histology%29&parcellationSelected=BigBrain+Cortical+Layers+Segmentation&cNavigation=0.0.0.-W000.._eCwg.2-FUe3._-s_W.2_evlu..7LIx..1n5q%7E.1FYC.2Is-.._r8
3. Cytoarchitectonic Maps: https://interactive-viewer.apps.hbp.eu/?templateSelected=Big+Brain+%28Histology%29&parcellationSelected=Cytoarchitectonic+Maps&cNavigation=0.0.0.-W000.._eCwg.2-FUe3._-s_W.2_evlu..7LIx..1n5q%7E.1FYC.2Is-.._r8

**Comment by pjtoussaint** [comment]
We already had the links provided by Timo:

**Cortical layers:**
*Viewer:*
https://interactive-viewer.apps.hbp.eu/?templateSelected=Big+Brain+(Histology)&parcellationSelected=BigBrain+Cortical+Layers+Segmentation

*Dataset card:*
https://kg.ebrains.eu/search/instances/Dataset/13e6ec48-4fec-4e9a-9bcf-45036d3c8ef9?group=curated

**Cytoarchitectural models:**
*Viewer:*
https://interactive-viewer.apps.hbp.eu/?templateSelected=Big+Brain+(Histology)&parcellationSelected=Cytoarchitectonic+Maps

*Dataset card:*
https://kg.ebrains.eu/search/instances/Project/af8d3519-9561-4060-8da9-2de1bb966a81?group=curated

**Comment by 3design** [comment]
updated links provided by Timo. Added  target="_blank" to open in new tab
