### ISSUE TITLE
New Featured Scholar video ready for release

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#152]
Please add a new Featured Scholar video to the youtube channel and to the Featured page
https://fz-juelich.sciebo.de/s/IJLRi2MUnac2bby
Also as a news card

Please add same descriptions to the video as for Konrad.

In both cases please add Name and Affiliation to the description, for Sofie it is:
Sofie Valk
Otto Hahn Group Cognitive Neurogenetics Max Planck Institute for Human Cognition and Brain Science, Germany
Cognitive Neurogenetics Group Institute of Neuroscience and Medicine (INM-7), Forschungszentrum Jülich, Germany

**Comment by SusanneWenzel** [comment]
Please add our standard links to the featured videos:

BigBrainProject https://bigbrainproject.org/ 
HIBALL https://bigbrainproject.org/hiball.html 
Twitter: @bigbrainproject

**Comment by 3design** [comment]
added

**Comment by SusanneWenzel** [comment]
@3design all good, thanks
