### ISSUE TITLE
New featured project

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#153]
Please add new featured project
https://drive.google.com/drive/folders/19GJNwasyJ8y1A3sEtbW3oiXahaiqpRQU?usp=sharing
also as a news card

**Comment by 3design** [comment]
- Put images in a row
- Code snippet
- larger font
- captions (make them more noticeable)

**Comment by 3design** [comment]
- experiment with 2 column layout
- increase font size
-

**Comment by SusanneWenzel** [comment]
@3design once we found our favourite layout, can you please apply it to the other featured blogs, too.

**Comment by 3design** [comment]
- remove top part of image (code)
- add comment to code: #copy this code to create the graphs
- look at styling for the code snippet
