### ISSUE TITLE
Update Human Brain NeHuBa Card to siibra explorer

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#154]
Please update the card Tools and Services / Visualization and Annotation / Human Brain NeHuba

New headline: ebrains siibra explorer
New text:  Browser-based viewer for visually exploring the EBRAIN atlases, including the BigBrain.
New link text: Open ebrains siibra explorer
New link: https://interactive-viewer.apps.hbp.eu/#/a:juelich:iav:atlas:v1.0.0:1/t:minds:core:referencespace:v1.0.0:a1655b99-82f1-420f-a3c2-fe80fd4c8588/p:juelich:iav:atlas:v1.0.0:4/@:0.0.0.-W000.._eCwg.2-FUe3._-s_W.2_evlu..7LIx..gIW~.10AwC.B1KK~..1LSm
Please open in a new tab

**Comment by SusanneWenzel** [comment]
Please change the Link text on all other cards linking to NeHuBa on this page as well --> Open ebrains siibra explorer

**Comment by 3design** [comment]
- update all links to siibra explorer on maps and models page
-

**Comment by SusanneWenzel** [comment]
ok
