### ISSUE TITLE
Unclear question in FAQ

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#159]
What table does the Q 'What are all the volumes....' refer to? Make clear in the question or in the text --> @pjtoussaint ?

**Comment by SusanneWenzel** [comment]
Solved at https://ftp.bigbrainproject.org/bigbrain-ftp/FAQ.html
Question is rephrased to 'What volumes of the BigBrain are available?'

**Comment by pjtoussaint** [comment]
Resolved.
