### ISSUE TITLE
FAQ How can I download the MINC volumes?

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#160]
Add a link here. @pjtoussaint please provide the correct link

**Comment by pj** [comment]
Hi @SusanneWenzel, I think you've tagged the wrong person :-).

**Comment by SusanneWenzel** [comment]
@pj Sorry my fault, will correct it

**Comment by SusanneWenzel** [comment]
Solved at https://ftp.bigbrainproject.org/bigbrain-ftp/FAQ.html
