### ISSUE TITLE
FAQ How do I view volumes online? Add new link

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#161]
TissueStack Link is not valid anymore, please correct if there is a new one. Or remove.
Also please add:
Explore the high resolution human brain model online in the [ebrains siibra explorer](https://interactive-viewer.apps.hbp.eu/#/a:juelich:iav:atlas:v1.0.0:1/t:minds:core:referencespace:v1.0.0:a1655b99-82f1-420f-a3c2-fe80fd4c8588/p:juelich:iav:atlas:v1.0.0:4/@:0.0.0.-W000.._eCwg.2-FUe3._-s_W.2_evlu..7LIx..gIW~.10AwC.B1KK~..1LSm)
Please open links in a new tab

**Comment by SusanneWenzel** [comment]
Solved at https://ftp.bigbrainproject.org/bigbrain-ftp/FAQ.html

**Comment by pjtoussaint** [comment]
Resolved.
