### ISSUE TITLE
Add new News Card 

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#170]
Markus Axer is the winner of the Helmholtz Imaging Best Scientific Image Contest 2021 with the image “The monkey’s fiber architecture revealed by Polarized Light” which shows the courses and orientations of nerve fibers in the cerebellum of a teenage vervet monkey brain.

[Video of the award ceremony](https://syncandshare.desy.de/index.php/s/eNr4WTiyqXb7qKx)

image:
https://drive.google.com/open?id=1E1IUmIjthyfeCO-_x2YvepW82eL2pPeu&authuser=swenzel.fzj%40gmail.com&usp=drive_fs

**Comment by SusanneWenzel** [comment]
Looks good. I'm not sure if we are allowed to "steal" the video. I know it's not comfortable, but please link to the original video.
Would the following fit the headline?
Markus Axer wins HIP scientific image contest

**Comment by 3design** [comment]
I've made the changes you suggested

**Comment by SusanneWenzel** [comment]
Thanks. The video in the card is still the youtube video :) please replace by the image and remove the image from our yt channel.
Name the link: 'video of the award ceremony'
Once the image is added to the community gallery you can also link to that

**Comment by SusanneWenzel** [comment]
@3design As you deleted the yt video the links at the News Card are broken, please fix.
Add image instead of the video, link to the original video source. Thx

**Comment by SusanneWenzel** [comment]
@3design all good now, thanks
