### ISSUE TITLE
News Card: Timo appointed W2 Professor at HHU

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#172]
Please add a News card

Timo Dickscheid was appointed W2 Professor at Computer Science Department, Heinrich-Heine-Universität Düsseldorf, Germany. 

Press Release (German)
https://www.math-nat-fak.hhu.de/aktuelles-1/aktuelles-detailansicht/dr-timo-dickscheid-zum-w2-professor-in-der-informatik-an-der-hhu-ernannt

Comment: Instead of W2 we could use Associated, although this translates not exactly, anyway would be ok

**Comment by SusanneWenzel** [comment]
@3design looks good, thanks

**Comment by 3design** [comment]
Change image to Timo's profile shot

**Comment by SusanneWenzel** [comment]
Looks good. Thanks

**Comment by pjtoussaint** [comment]
Approved.
