### ISSUE TITLE
add 'how to cite' to card

### ISSUE THREAD

**Issue by 3design** [3design/3design.github.io#176]
As per the meeting, add how to cite to the license card on the maps and models page

**Comment by SusanneWenzel** [comment]
The aspect ration of cards on the maps&models page is somehow broken!?
As the card does not allow C&P there should be another way to copy the reference, maybe provide a download link to a bib or txt-file or directly to the clipboard, if the latter is possible?
I also wonder if the position of that card is confusing. Actually it refers to the first 2 cards only, for cytoarchitectonic maps and cortical layers different references are valid and given in the Atlas Viewer. @pjtoussaint what do you think? Can we merge license and reference into one card, next to the data?

**Comment by 3design** [comment]
@SusanneWenzel I corrected the aspect ratio i believe. please check again. As well, the card allows for cut/paste on my computer. could you please verify that you cannot highlight the text?

**Comment by SusanneWenzel** [comment]
@3design aspect ratio looks good now and I'm now able to C&P the text

**Comment by pjtoussaint** [comment]
Looks good!
