### ISSUE TITLE
Change structure News & Events

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#18]
I'd propose the following structure
- Headline: BigBrain News and Events
no sub header

- Section: News
does it make sense to simply copy the slider from the landing page here?

- Section: BigBrain and HIBALL events
slider with events from our consortium
for now: BigBrain Workshop, Talk Blake 6.7.

- Section: related events
slider with conferences etc. related to the BigBrain Community, e.g. MIDL, OHBM & co

- Section: Archive News
slider old news (proposal: everything older than 3 month or everything above 5 items in the news and older than one month)

- Section: Archive events
slider with past event, eg former BigBrain Workshops

**Comment by 3design** [comment]
will need to chat about how this will be visualized. reserved for conversation before proceeding
