### ISSUE TITLE
Please reopen the job page and post a new position

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#190]
https://www.fz-juelich.de/SharedDocs/Stellenangebote/_common/dna/2022-150-EN-INM-1.html?nn=363488

rather urgent as deadline is May 15 already

**Comment by 3design** [comment]
@SusanneWenzel @pjtoussaint Ready for review and push to production if approved

**Comment by SusanneWenzel** [comment]
Please add:

bold: **To strengthen our Helmholtz AI research group and activities at HHU, we are looking for an experienced**
large and bold **Postdoc in Machine Learning for Microscopic Image Analysis**
with line breaks

line break before link

Deadline is redundant, can be removed in the text

Could you make the font size larger? ^^

**Comment by 3design** [comment]
@SusanneWenzel I've put in the first sentence in bold and removed the date inside the text. I've also added line breaks to the text itself. Please check

**Comment by SusanneWenzel** [comment]
:) please remove the style info :)

The text doesn't tell much about the job, it is just the intro. Lets take this:

If you are into ML & image analysis and interested in the microstructure of the brain, please apply to join INM-1 in Jülich: 

**To strengthen our Helmholtz AI research group and activities at HHU, we are looking for an experienced**
**Postdoc in Machine Learning for Microscopic Image Analysis**

**Comment by 3design** [comment]
@SusanneWenzel Updated the text with what you proposed above

**Comment by SusanneWenzel** [comment]
@3design perfect. Thank!

**Comment by SusanneWenzel** [comment]
@3design Could you please  add a News Card to point people to the call. Just like: New job opportunity --> link to the career page
