### ISSUE TITLE
Add news card about visit of Trudeau and Scholz at MILA

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#211]
Visit of German Chancellor and Canadian Prime Minister at MILA 
August 22, 2022

German Chancellor Olaf Scholz and Prime Minister Justin Trudeau visit MILA and met Yoshua Bengio, Katrin Amunts, Alan Evans. They led a discussion on drug discovery and brain mapping and brought forth unique research collaborations between German and Canadian research centres. 

press:
https://www.cscience.ca/2022/08/22/alliance-entre-lallemagne-et-le-canada-le-chancelier-olaf-scholz-de-passage-a-mila/
https://mila.quebec/en/mila-welcomes-german-chancellor-olaf-scholz-prime-minister-justin-trudeau-and-global-business-leaders-to-its-spaces/

image: https://drive.google.com/file/d/1BmELnUXKSTINR09pKEKS0wvaf7Dn9KKm/view?usp=sharing
Caption: 3D-printed model of the BigBrain, which is now being displayed in the German embassy in Ottawa.

**Comment by 3design** [comment]
Add "3D-printed model of the BigBrain, which is now being displayed in the German embassy in Ottawa" to body text
