### ISSUE TITLE
Create page for BigBrain Workshop 2022

### ISSUE THREAD

**Issue by 3design** [3design/3design.github.io#218]
based on the Winterschool page, with modifications

**Comment by SusanneWenzel** [comment]
@3design 
text and images: https://docs.google.com/document/d/1g6TckQ8kDLxAmLXjkQvKmtZF8Bn-RL8Ne3167SY4m1I/edit?usp=sharing
videos are ready: https://drive.google.com/open?id=1L_Zya02iglFtqJimRVQ3oKl7ErsdZkf8&authuser=swenzel.fzj%40gmail.com&usp=drive_fs

**Comment by SusanneWenzel** [comment]
@3design images for a gallery are also available now
https://drive.google.com/open?id=1NhfY--kqwSqaq7bvSen87MpnZX63urzT&authuser=swenzel.fzj%40gmail.com&usp=drive_fs

**Comment by 3design** [comment]
> @3design images for a gallery are also available now https://drive.google.com/open?id=1NhfY--kqwSqaq7bvSen87MpnZX63urzT&authuser=swenzel.fzj%40gmail.com&usp=drive_fs

@SusanneWenzel Thanks for the images. I'm not too sure how to insert these images into the page. Should I continue the gallery 'slider'? If so, I'll need text with each image

**Comment by SusanneWenzel** [comment]
@3design What about putting the 'selected images' with caption into the text and have a gallery without captions only? Otherwise, could we have two galleries?

Could you please increase font size of the text (a lot ^^ ). Maybe two columns, as for the featured projects? Depends how you place the pictures. Also adapt font sizes in image gallery (if it stays). Do we need actually need two different fonts here?

Logos: make sure to have similar sizes, HBP way too large currently. Jagma below the project's logos. I.e., first row: FZJ, McGill, second row: Helmholtz, HBHL, HBP, third row: jagma

**Comment by 3design** [comment]
Increased font size of text to that of the featured pages. Also split the text into two columns. Rearranged logos below text. Pushed images for the gallery (haven't set it up yet).

@SusanneWenzel Do you want to use all the images in the gallery folder?

**Comment by pjtoussaint** [comment]
Perhaps add a card with text such as: "More photos" or "Visit our gallery" - that would lead to a page with all other photos.

**Comment by 3design** [comment]
@pjtoussaint sure! I can set up a second page with the images in a grid. That would reduce the need to scroll so much to reach the videos

**Comment by SusanneWenzel** [comment]
@pjtoussaint do you think its to much images? @3design We can reduce, if you like. I'll anyway share more pictures with the participants. But these I thought would be nice to have at the page to give an impression about the event. What about having to sliders? If there are no captions pictures would be next to each other.

**Comment by SusanneWenzel** [comment]
Can you please make the font even larger? About 3x at least, also at the image captions (except headings)
Also spacing between lines larger (general comment for whole page). I know I'm being a pain, sorry for that
Please make HBP logo smaller.

**Comment by 3design** [comment]
@SusanneWenzel no worries. I've increased the line spacing for the text area in the two columns. Also reduced the HBP logo size and re-added the logos to the beginning of the page
