### ISSUE TITLE
Broken links to atlas viewer

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#219]
Xiao found some old url to the atlas viewer, i.e. https://interactive-viewer.apps.hbp.eu/ instead of https://atlases.ebrains.eu/viewer/

If we could get (automatically?) all hyper links, which contain the string, https://interactive-viewer.apps.hbp.eu/, he would provide a mapping to the update url

**Comment by 3design** [comment]
for now we have 4 links on the maps and models page that need updating

**Comment by SusanneWenzel** [comment]
Please replace in all these urls the first part of the url, i.e.
https://interactive-viewer.apps.hbp.eu/
with
https://atlases.ebrains.eu/viewer/
The remaining urls should remain the same

**Comment by SusanneWenzel** [comment]
UPDATE: Xiao suspects that there might be edge cases where a simple replacement does not work. I clarify with him to to proceed.

**Comment by 3design** [comment]
@SusanneWenzel Thanks for finding the additional links. I have updated the tools page, maps page, and about page. Tested the links and they seem to load the viewer correctly.

**Comment by SusanneWenzel** [comment]
**Maps and Models**

- Cortical Layer Maps do not work anymore
Please use this link: https://atlases.ebrains.eu/viewer/#/a:juelich:iav:atlas:v1.0.0:1/t:minds:core:referencespace:v1.0.0:a1655b99-82f1-420f-a3c2-fe80fd4c8588/p:juelich:iav:atlas:v1.0.0:3/@:0.0.0.-W000.._eCwg.2-FUe3._-s_W.2_evlu..7LIy..9teY~.GW6K.b1lI..1sst

- Cyto Maps ok

- One micron sections do not work anymore
This one seem to be tricky. Can not reuse an url. Will ask Xiao about that

- Links in Q&A all ok now

Could you please set all links per default to be open in a new tab

**Comment by SusanneWenzel** [comment]
all good. Xiao will change the link to the 1micron section and will raise a separate PR

**Comment by xgui3783** [comment]
Please see https://github.com/3design/3design.github.io/pull/237 for the PR
