### ISSUE TITLE
change list of additional people at About/BigBrain team the people from the original paper

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#22]
As long as we can not restore the history of the list of people below the original authors, we should restrict to those mentioned in the paper:
Patricia Morosan
Uwe Pietrzyk
Ferdag Kocaer
Ursula Blohm 
Reza Adalat

@pj please correct, if you find the old Email from Katrin

please sync description of people with picture to those from the Hiball picture wall

**Comment by 3design** [comment]
remove sub header
