### ISSUE TITLE
replace FZJ links

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#221]
We have a new CMS and links to FZJ changed.
Can you fetch all links starting with https://www.fz-juelich.de
I'll create the according replacements

Meanwhile, at the HIBALL wall you can replace already
https://www.fz-juelich.de/inm/inm-1/EN/Home/home_node.html  with
https://www.fz-juelich.de/en/inm/inm-1
and
https://www.fz-juelich.de/inm/inm-7/EN/Home/home_node.html  with
https://www.fz-juelich.de/en/inm/inm-7
and
https://www.fz-juelich.de/ias/jsc/EN/Home/home_node.html    with
https://www.fz-juelich.de/en/ias/jsc

**Comment by 3design** [comment]
@SusanneWenzel I checked the code and I did indeed run a find/replace for the above. I just checked a few links on the https://bigbrainproject.org/hiball.html page and so far they seem to work. Can you let me know which profile is broken so I can fix the missing one?

**Comment by SusanneWenzel** [comment]
- remove: Chadi Barakat, Charlotta Eick, Daviti Gogshelidze, Kai Kiwitz, Svenja Kuechenhoff, Sascha Münzing
- Seyma Bayrak - replace name, if possible, Şeyma Bayrak ; replace link https://www.fz-juelich.de/de/inm/inm-7/additional-profiles/m-sc-seyma-bayrak
- Sebastian Bludau --> [Institute for Neuroscience and Medicine, Structural and functional organisation of the brain (INM-1)](https://www.fz-juelich.de/en/inm/inm-1)    NOT INM-7
- Timo Dickscheid - replace link https://www.fz-juelich.de/profile/dickscheid_t (typo)
- Simon Eickhoff - replace link https://www.fz-juelich.de/en/inm/inm-7/research-groups/systems-medicine
- Thomas Funck - replace link https://childmind.org/bio/thomas-funck-phd/
- Xiao Gui - use the image from his website
- Meike Hettwer - replace link https://www.fz-juelich.de/profile/hettwer_m
- Jan-Oliver Kropp - add link https://www.fz-juelich.de/profile/kropp_j
- Marcel Huysegoms - replace link https://www.fz-juelich.de/profile/huysegoms_m (typo)
- Thomas Lippert - replace link https://www.fz-juelich.de/profile/lippert_th
- Neville Magielse - replace link https://www.fz-juelich.de/profile/magielse_n
- Mohammad Shahbaz Memon - remove link (no page at all currently) 
- Meiqi Niu - add link https://www.fz-juelich.de/profile/niu_m
- Nicola Palomero-Gallagher - replace link https://www.fz-juelich.de/en/inm/inm-1/research/receptors
- Casey Paquola - replace affiliation [Institute for Neuroscience and Medicine, Brain and Behaviour (INM-7)](https://www.fz-juelich.de/en/inm/inm-7) ; replace name Casey Huysegoms; replace link https://www.fz-juelich.de/profile/huysegoms_c
- Amin Saberi - add link https://www.fz-juelich.de/profile/saberi_a
- Lina Schaare - replace link https://www.fz-juelich.de/profile/schaare_l
- Eric Upschulte - add link https://www.fz-juelich.de/profile/upschulte_e
- Sofi Valk - replace link https://www.fz-juelich.de/en/inm/inm-7/research-groups/cognitive-neurogenetics
- Bin Wan - replace link https://www.fz-juelich.de/profile/wan_b
- Lyuba Zehl - remove link (have to add the new one asa available)

**Comment by SusanneWenzel** [comment]
@3design could you please copy over these descriptions to the cards at https://3design.github.io/about.html , where applicable. If in doubt remove the personal links
For Karl Zille the text is too long and not readable at all. We should add an info '1.4.1944 - 26.4.2020' and refer to his former positions only, such that it fits. @pjtoussaint maybe you find a formulation that appreciates his contributions to the project

**Comment by SusanneWenzel** [comment]
@3design can you please let me know where else fzj links appear
