### ISSUE TITLE
Add -- HIBALL | Boards: add descriptive text

### ISSUE THREAD

**Issue by pjtoussaint** [3design/3design.github.io#231]
Please add the following to the corresponding photo wall: 

Steering Board: 

The Steering Board (SB) leads the scientific work and activities of HIBALL. The SB is constituted by the speakers of the scientific work packages and their deputies. The SB meets on a regular basis to streamline activities between all work packages and provides annual periodic reports about scientific progress and HIBALL’s activities to our funding bodies: the [Helmholtz Association](https://www.helmholtz.de/en/) and [Healthy Brains, Healthy Lives](https://www.mcgill.ca/hbhl/).

Scientific Advisory Board: 

The Scientific Advisory Board (SAB) monitors HIBALL’s scientific activities and continuously provides advice on the scientific developments to the SB. The SAB makes sure that the work carried out in HIBALL is scientifically relevant and corresponds to the current state of the art. The SAB meets regularly and participates in the yearly BigBrain Workshop.

**Comment by SusanneWenzel** [comment]
@3design can you align images and text? I.E. move at least one image from the SB to the next line and move SAB images closer together? Right and left alignment of text and images would be great. Does that work?
SB: Please move Bratislav between Morris and Blake (would fit the WPs this way)
In the menu: Board --> Boards

**Comment by 3design** [comment]
please look at the following changes https://3design.github.io/board.html

**Comment by SusanneWenzel** [comment]
@3design looks good. thank you
