### ISSUE TITLE
add new featured project - voluba

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#234]
Please add a new featured project 
Voluba

text and images at /Shared drives/BigBrainProject/Website/FeaturedSeries/23-04-voluba

**Comment by SusanneWenzel** [comment]
Could you align the "icon paragraphs" somehow, such that all go into one (virtual) box ? Intro and outro could go on top or bottom. Will that work?

**Comment by 3design** [comment]
As of last push, I have moved all the bullet points with icons to the right column, and the outro to the first column

**Comment by 3design** [comment]
@SusanneWenzel  I have put the outro at the bottom of the left column already :)

I will create a news. card for the front page and the featured section for the next push

**Comment by SusanneWenzel** [comment]
For me, the outro is still right below the intro. I did refresh ;)
<img width="693" alt="image" src="https://github.com/3design/3design.github.io/assets/29659187/39085d00-3694-487c-8cac-06221b15ed5a">

**Comment by 3design** [comment]
@SusanneWenzel I understand I think. I added margin on top to push the outro down closer to the bottom of the column. This only appears when the page is at 2 column layout (min 800px screen width)

**Comment by SusanneWenzel** [comment]
Perfect, thanks.
