### ISSUE TITLE
add new featured paper blog post on laminar thickness profiles

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#236]
Please add a new blog post as featured paper by Amin Saberi
Text and images are in our featured folder
23-05-spatial_arrangement_of_laminar_thickness_profiles

**Comment by SusanneWenzel** [comment]
@3design could you please release this one now ?

**Comment by 3design** [comment]
@SusanneWenzel Sorry Susanne, I didn't see your previous message until now. I've uploaded the paper to https://3design.github.io/featured-paper-7.html and it should update in the next 10 minutes
