### ISSUE TITLE
add OHBM Blog Posts to events page

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#249]
Please put the two OHBM blog posts also to our events page.

**Comment by 3design** [comment]
@SusanneWenzel The two blog posts are in the bigbrain news archive. Is this correct? 

https://bigbrainproject.org/news.html#tabs-1

**Comment by SusanneWenzel** [comment]
@3design I see, my fault. The OHBM Project at OHBM could move to events, Brain and Arts at News archive is fine
