### ISSUE TITLE
Add 7th BB Workshop page

### ISSUE THREAD

**Issue by 3design** [3design/3design.github.io#251]
Add 7th BB Workshop page and linked gallery page

**Comment by 3design** [comment]
@SusanneWenzel @pjtoussaint Page is up and ready for review

https://3design.github.io/bigbrainworkshop-2023.html

**Comment by SusanneWenzel** [comment]
@3design Great! Thank you!
* Could you please add all logos from the workshop's website https://events.hifis.net/event/716/overview. I.e., replace U o Iceland Logo and add ebrains and cbrain
* In the video descriptions, please replace the link to the workshop website with https://go.fzj.de/BigBrainWorkshop2023 (abstract links remain the same)
* Headline 'Day 1 Talks' ==> 'HBHL Training Day'
* Combine Sections 'Day 2 Talks' and 'Day 3 Talks', new headline: 'BigBrain Workshop Talks'
@pjtoussaint Shall we sort invited talks on top? I.E. move up
Kári Stefánsson
Paul M. Thompson
Pedro Valdés-Sosa
Viktor Jirsa
Panel discussion Day 2
LOC Session, Magnús Örn Úlfarsson
LOC Session, Ragnhildur Thóra Káradóttir
LOC Session, Lotta María Ellingsen

**Comment by 3design** [comment]
Hi @SusanneWenzel 

- In regards to the logos, if I add more logos to the top box, the box gets too big for smaller screen sizes. In this case I would recommend adding a section like in https://3design.github.io/bigbrainworkshop-2022.html that has a description of the workshop as well as all the logos from https://events.hifis.net/event/716/overview. How do you feel about that?
- for the video descriptions, am I just changing the link text to read abstract: https://go.fzj.de/BigBrainWorkshop2023 but keeping a direct link to the abstract itself?

**Comment by SusanneWenzel** [comment]
1. Agree! In that case, only keep the first row of logos and move everything else to a separate section.
2. Only change the main link on top to the landing page and please keep the abstract links. If I'm right the go.fzj link only forwards to the landing page and does not work for subpages, i.e. abstracts

**Comment by 3design** [comment]
For the links, I'm still a little confused. I have made the following edit (see picture). The link is still intact but the text shows the go.fzj.de 

here is the code snippet

`Abstract: <a href="https://events.hifis.net/event/716/page/127-bigbrain-project-educational-lecture"> https://go.fzj.de/BigBrainWorkshop2023</a>`

![Screen Shot 2024-01-10 at 1 28 37 PM](https://github.com/3design/3design.github.io/assets/16245024/54ab85b5-12b2-418b-8d34-d14e7c9888c2)

**Comment by 3design** [comment]
![logo-euro2](https://github.com/3design/3design.github.io/assets/16245024/e490b232-e8a0-43e3-a57c-d236c8beca17)

Is there a website link for this logo? I can't seem to find one

**Comment by SusanneWenzel** [comment]
> For the links, I'm still a little confused. I have made the following edit (see picture). The link is still intact but the text shows the go.fzj.de
> 
> here is the code snippet
> 
> `Abstract: <a href="https://events.hifis.net/event/716/page/127-bigbrain-project-educational-lecture"> https://go.fzj.de/BigBrainWorkshop2023</a>`
> 
> ![Screen Shot 2024-01-10 at 1 28 37 PM](https://private-user-images.githubusercontent.com/16245024/295669350-54ab85b5-12b2-418b-8d34-d14e7c9888c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTc4NDEsIm5iZiI6MTcwNDk1NzU0MSwicGF0aCI6Ii8xNjI0NTAyNC8yOTU2NjkzNTAtNTRhYjg1YjUtMTJiMi00MThiLThkMzQtZDE0ZTdjOTg4OGMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA3MTkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MzkyYzhiZTI5ZjUwNTI3OWRhMzJiZDE3Yjc2NWVhMmU3ZWQ1YWY3ZWQ2Y2JiZTZlNDdhOGQ2MGU3ZjA5YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DQGhe9ZEJlLKYqzcQDSeeFQC74nwUdQF_90LicKxpac)

I see, my fault, I wasn't precise enough. I was referring to the video descriptions at YT. See picture.
go.fzj.de/BigBrainWorkshop2023 is just an alias for https://events.hifis.net/event/716/.
So, please only replace the link to the workshop registration website in the YT descriptions and keep the abstract links as they were

![Screenshot 2024-01-11 at 08 20 14](https://github.com/3design/3design.github.io/assets/29659187/6366cded-6ab7-4640-aa52-e97a0362adfa)

**Comment by SusanneWenzel** [comment]
> ![logo-euro2](https://private-user-images.githubusercontent.com/16245024/295675901-e490b232-e8a0-43e3-a57c-d236c8beca17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTc4NDEsIm5iZiI6MTcwNDk1NzU0MSwicGF0aCI6Ii8xNjI0NTAyNC8yOTU2NzU5MDEtZTQ5MGIyMzItZThhMC00M2UzLWE1N2MtZDIzNmM4YmVjYTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA3MTkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyOGFlMzE5YWRkYjVlNGViM2NiN2VmY2JlODc5OGEyNTRmZWYzMGNkMTgyMmY3YzVmYzg5ZmZjMTM0NjQ3ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.carCa_cns02EdfcjhQiUGX2WMq4nM6bWOwVHpKjvbSw)
> 
> Is there a website link for this logo? I can't seem to find one

Should be this one: https://www.eurocc-access.eu/

**Comment by 3design** [comment]
> * https://go.fzj.de/BigBrainWorkshop2023

I understand now! I have updated all the youtube descriptions

**Comment by 3design** [comment]
https://3design.github.io/bigbrainworkshop-2023.html

**Comment by SusanneWenzel** [comment]
Could you move the logo section to the very bottom? 
@pjtoussaint what is your opinion on resorting the BBWS talks as proposed above? I.e. moving all invited talks on top.
Otherwise, it looks very good to me! Thank you!

**Comment by pjtoussaint** [comment]
@SusanneWenzel @3design : we could add a section 'Invited Talks' with only the list of speakers and links to YT. For the sake of clarity I would keep the rest as is - i.e. matching the programme and schedule for each day.

**Comment by SusanneWenzel** [comment]
@pjtoussaint @3design ok, also fine

**Comment by 3design** [comment]
@pjtoussaint Should I put back the header for day 2 and day 3 talks?

**Comment by 3design** [comment]
@pjtoussaint @SusanneWenzel I have added the speakers to the highlights gallery with anchor links to the videos. I have noticed that the links to the videos are delayed until all the youtube previews have loaded. That means that a user will have to wait for a full page load before they can use the links

**Comment by pjtoussaint** [comment]
It looks good.
Shall we also add the speakers affiliations to the highlights gallery?
