### ISSUE TITLE
add YT link to teaching card

### ISSUE THREAD

**Issue by 3design** [3design/3design.github.io#257]
Add the youtube link to the teaching card on the community page

**Comment by SusanneWenzel** [comment]
@3design Please change Teaching card description
Upcoming teaching events and materials.
==> Videos from our teaching events
(Or similar)

**Comment by 3design** [comment]
@SusanneWenzel I've changed the text on the card and button. I'm wondering if the text needs to be revised more. The button leads to past event videos so maybe we should alter the text of the card so that it isn't about upcoming events. Just a thought :)
