### ISSUE TITLE
Add news card about MNI visitor in Germany

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#260]
Please add a news card 

Yezhou Wang is visiting Sofie Valk's lab in Leipzig for a three-month mitacs research stay to work on 'Capturing patterns of cortical hierarchy and dual stream architecture based on precise 7T MRI' 

@pjtoussaint ok?

image will be sent soon

**Comment by 3design** [comment]
@SusanneWenzel Just waiting for image before adding the card

**Comment by SusanneWenzel** [comment]
![IMG_20240508](https://github.com/3design/3design.github.io/assets/29659187/45d207ed-1cc4-4938-96de-2cc831f83f89)
@3design image uploaded :)

**Comment by 3design** [comment]
- [ ] add link to sophies lab (see card in news)
