### ISSUE TITLE
Add news about OHBM presence 

### ISSUE THREAD

**Issue by 3design** [3design/3design.github.io#262]
Add a card about being present at OHBM booth 203 (news and events page)

**Comment by SusanneWenzel** [comment]
Please update:
image: 
![WhatsApp Image 2024-07-09 at 09 30 22](https://github.com/3design/3design.github.io/assets/29659187/aaa9d7f4-004d-444f-9f4b-9ce92c2e2409)
text:
The HIBALL Team presented the BigBrain data and tools at the annual OHBM meeting in Seoul, South Korea on June 23-27, 2024. It was fun to meet the community and discuss multimodal, high-resolution neuroscientific data and tools.

**Comment by 3design** [comment]
@SusanneWenzel Should this card be added to the NEWS ARCHIVE on the community>news & events page?

**Comment by SusanneWenzel** [comment]
@3design good point, yes. For a while it can also be under news on the landing page
