### ISSUE TITLE
Update Lyuba Zehls card

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#265]
Please update Lyuba Zehl's card
personal link: https://www.linkedin.com/in/lyuba-zehl/?originalSubdomain=de
Affiliation: EBRAINS AISBL [https://www.ebrains.eu/]

**Comment by 3design** [comment]
@SusanneWenzel For the personal link, the user must be logged in to linkedin in order to see the page. Are you okay with this?

**Comment by SusanneWenzel** [comment]
hm, ok, not good. Anyway, it seems Lyuba doesn't have another page currently. Just keep it for now please
