### ISSUE TITLE
Update download link cortical layer maps

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#266]
https://bigbrainproject.org/maps-and-models.html
Card cortical layer maps
please change 'download' link to:
https://search.kg.ebrains.eu/instances/13e6ec48-4fec-4e9a-9bcf-45036d3c8ef9
(This one does not require login. Please test!)

**Comment by 3design** [comment]
@SusanneWenzel yes it seems to go to the dataset information page and doesn't ask for a login
