### ISSUE TITLE
Community/Videos - Link to YT channel

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#270]
https://bigbrainproject.org/community.html
Section videos
Please add a hint about the BigBrain Project's YT Channel

**Comment by 3design** [comment]
@SusanneWenzel Do you mean add a card or a link that directs the user to the bigbrainproject youtube channel?

https://www.youtube.com/channel/UCAxNz4exfs6mxagb3Ufq7-w

**Comment by SusanneWenzel** [comment]
I thought about a line of text with the link. But maybe you're right, a card would also make sense. Would it be possible to have such a card static in first place?

**Comment by 3design** [comment]
I can add a line of text under the subtitle with the youtube channel link no problems.

Alternately, I can add a card to the slider that is in the first position, but it will move with the slider.

To add a card that is permanently in the first position, I think I will need to rewrite some of the code for the page. It can be done though. 

Which option do you prefer?

**Comment by SusanneWenzel** [comment]
Take the most simplest solution! It is just to let visitors know, that there is much more to explore

**Comment by 3design** [comment]
haha no problems!
