### ISSUE TITLE
Add new publication to refs

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#36]
Publication from the BigBrain Community, Neuro members co-authors
new citation of the BigBrain
https://www.researchgate.net/publication/342682075_Transcriptomic_and_cellular_decoding_of_regional_brain_vulnerability_to_neurogenetic_disorders

**Comment by pjtoussaint** [comment]
Seidlitz J, Nadig A, Liu S, Bethlehem RAI, Vértes P, Morgan S, Váša F, Romero-García R, Lalonde F, Clasen L, Blumenthal J, Paquola C, Bernhardt B, Adler-Wagstyl K, Polioudakis D, Torre-Ubieta L, Geschwind D, Han J, Lee N, Raznahan A (2020) Transcriptomic and cellular decoding of regional brain vulnerability to neurogenetic disorders. Nature Communications. 11. 10.1038/s41467-020-17051-5. 

https://www.nature.com/articles/s41467-020-17051-5
