### ISSUE TITLE
Add page for the BigBrain Workshop, releasing slides and videos

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#38]
Draft: https://docs.google.com/document/d/1AQWcNSbal4T8KwavyWc05vi2AdgT8mHsr4Cx9pf3Ffs/edit?usp=sharing

**Comment by pjtoussaint** [comment]
Pending materials...

**Comment by 3design** [comment]
add new card on upcoming bb events page. This will link to a unique page to display the video content

**Comment by SusanneWenzel** [comment]
I updated https://docs.google.com/document/d/1yLNZUnyVO_HVOwBXEZyVGZiNRqfE5oOuVHijnyZMG6s/edit?usp=sharing . It contains timestamps for all talks now.

**Comment by SusanneWenzel** [comment]
> add new card on upcoming bb events page. This will link to a unique page to display the video content

upcoming and past events, I guess?

**Comment by SusanneWenzel** [comment]
Our HBP PR officer has looked over the texts at the googledoc draft and would not want to add anything, he thinks it is ok. I think the layout has to find a good compromise between images (size) and text

**Comment by SusanneWenzel** [comment]
all slides as pdf available now at /Google Drive/HIBALL_coordination_team/Kick-Off-Meeting/talks_slides/pdf4webpage
