### ISSUE TITLE
FAQ: Add citation box

### ISSUE THREAD

**Issue by pjtoussaint** [3design/3design.github.io#42]
Q: How to cite

A:
When referring to the BigBrain Project or using the data, please cite the original Science 2013 publication: 

Amunts K, Lepage C, Borgeat L, Mohlberg H, Dickscheid T, Rousseau M-É, Bludau S, Bazin PL, Lewis LB, Oros-Peusquens AM, Shah NJ, Lippert T, Zilles K, Evans AC. BigBrain: An ultrahigh-resolution 3D human brain model. Science. 2013; 340(6139):1472-1475. doi: 10.1126/science.1235381. PMID: 23788795.

**Comment by 3design** [comment]
This was done in a previous version. I have cut/pasted the copy from this issue into place and the only difference is Q: How to cite [BigBrain] <-- this was removed. Pushed to github
