### ISSUE TITLE
Add News about HBP Partnering Project

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#44]
HIBALL is now part of the HBP community. We are looking forward to contribute to the HBP as Partnering Project
https://www.humanbrainproject.eu/en/about/project-structure/partnering-projects/hiball/

**Comment by 3design** [comment]
@SusanneWenzel This link is now 404. Do you know of a different url for this?

**Comment by SusanneWenzel** [comment]
Thanks for the hint, there is sth broken. I'll contact the HBP web developers.

**Comment by SusanneWenzel** [comment]
fixed :)
