### ISSUE TITLE
Add pictures HIBALL team

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#51]
Images of Tristan Glatard and Valerie Hayot-Sasson now available at 
/Google Drive/HIBALL_coordination_team/BigBrainProject_Webpage/images/HIBALLpeople

**Comment by 3design** [comment]
Added Valerie. I am waiting for Tristan to send a larger image of himself (I may be able to steal the one from his Concordia profile if it's still up).

I will also need details for them: Job title and/or institution as well as a link if they'd like it included.

**Comment by 3design** [comment]
I retrieved a higher resolution image for Tristan on the concordia staff website.

**Comment by SusanneWenzel** [comment]
> Added Valerie. I am waiting for Tristan to send a larger image of himself (I may be able to steal the one from his Concordia profile if it's still up).
> 
> I will also need details for them: Job title and/or institution as well as a link if they'd like it included.

information added to the table

**Comment by SusanneWenzel** [comment]
Also Casey Paquola's image now available in the GoogleFolder
