### ISSUE TITLE
! Links to yt video not correct

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#56]
Some links are not properly set, please correct
I'm not sure whether it is due to cookies at my local machine whereof links lead to the point where I stopped last time. To be on the save time, all links should have time stamp, I suppose.

I refer to full names of the links
- Opening Remarks
- Towards automated mapping of cytoarchitectonic areas using Deep Learning --> definitive wrong video ;)
- Lightning Talks

**Comment by 3design** [comment]
corrected Timo video link. Investigating other issue though I believe it's a cookie that keeps track of the playhead location.

**Comment by SusanneWenzel** [comment]
I see, thanks
