### ISSUE TITLE
hiball-launch: add video Pedro, add pdfs Pedro and Thomas

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#57]
Please add contribution of Pedro Valdes-Sosa to Lightning talks, video and pdf.
Please add slides for Thomas Funck's talk

PDFs: /Google Drive/HIBALL_coordination_team/Kick-Off-Meeting/talks_slides/pdf4webpage/
Video: /Google Drive/HIBALL_coordination_team/Kick-Off-Meeting/videos/20-06-26-BigBrainWorkshop-Valdes-Sosa.mp4

video quality to be checked

**Comment by 3design** [comment]
Also replace the pdf fro Sacha van Albada

**Comment by 3design** [comment]
updated youtube with a new lightning talk video https://youtu.be/yM0I_4arCWU
this includes Pedro's re-encoded video (sound correction) 
updated youtube time indices to match new start times
updated hiball-launch.html to reflect above changes
added Pedro's slides to docs
