### ISSUE TITLE
new News Card

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#70]
New article on nature scientific reports. 
Deep learning networks reflect cytoarchitectonic features used in brain mapping. 
Kai Kiwitz, Christian Schiffer, Hannah Spitzer, Timo Dickscheid & Katrin Amunts
https://www.nature.com/articles/s41598-020-78638-y

**Comment by pjtoussaint** [comment]
Change "on" to "in": 
New article in nature scientific reports.
