### ISSUE TITLE
New entry for publications

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#71]
Kiwitz, K., Schiffer, C., Spitzer, H., Dickscheid, T., Amunts, K. Deep learning networks reflect cytoarchitectonic features used in brain mapping. Sci Rep 10, 22039 (2020). https://doi.org/10.1038/s41598-020-78638-y

**Comment by pjtoussaint** [comment]
Kiwitz K, Schiffer C, Spitzer H, Dickscheid T, Amunts K (2020) Deep learning networks reflect cytoarchitectonic features used in brain mapping. Sci Rep 10, 22039. https://doi.org/10.1038/s41598-020-78638-y
