### ISSUE TITLE
urgent: add open positions as News

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#72]
Please add open positions as news cards to the landing page. We don't have a dedicated space for that, do we?

1. W1 Junior Professorship Transfer Learning for microscopic image analysis
link coming soon
Deadline January 31, 2021

2. Postdoc position at the Institute for Neuroscience and Medicine, Structural and Functional Organisation of the Brain (INM-1) 
https://www.fz-juelich.de/SharedDocs/Stellenangebote/_common/dna/2020-414-EN-INM-1.html?nn=722362
Deadline January 12, 2021

3. Software Community Manager
https://www.fz-juelich.de/SharedDocs/Stellenangebote/_common/dna/2020-402-EN-INM-1.html?nn=722362
deadline  January 31, 2021

**Comment by 3design** [comment]
I have created a careers page nested under community using the references template. It appears on 3design.github.io

**Comment by SusanneWenzel** [comment]
perfect, thanks! I let you know as soon as the prof call is out
