### ISSUE TITLE
Add new publication

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#76]
https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3000979

**Comment by 3design** [comment]
Casey Paquola, Jakob Seidlitz, Oualid Benkarim, Jessica Royer, Petr Klimes,Richard A. I. Bethlehem, Sara Larivière, Reinder Vos de Wael, Raul Rodríguez-Cruces, Jeffery A. Hall, Birgit Frauscher, Jonathan Smallwood, Boris C. Bernhardt (2020) A multi-scale cortical wiring space links cellular architecture and functional dynamics in the human brain. PLOS BIOLOGY: link

please revise if incorrect

**Comment by 3design** [comment]
code pushed to github

**Comment by SusanneWenzel** [comment]
looks good, thanks

**Comment by pjtoussaint** [comment]
Shall we try to be consistent with the reference style: 

Paquola C, Seidlitz J, Benkarim O, Royer J, Klimes P, Bethlehem RAI, Larivière S, Vos de Wael R, Rodríguez-Cruces R, Hall JA, Frauscher B, Smallwood J, Bernhardt BC (2020) A multi-scale cortical wiring space links cellular architecture and functional dynamics in the human brain. PLoS Biology 18(11): e3000979. link

**Comment by SusanneWenzel** [comment]
@3design is there a way to automatically import references from a database (zotero, bibtex, whatever), i.e., sth like a plugin? This would automatically generate a unique style for all refs and prevents redundancies if we refer to that database from all places

**Comment by pjtoussaint** [comment]
@SusanneWenzel:  We do not have that large a number of publications appearing per month (yet) to justify setting up an automatic solution. 
I would suggest that we continue to add this information manually, keeping to a single style as much as possible. 
In the meantime we can freely explore existing solutions or plugins for future implementation.

**Comment by SusanneWenzel** [comment]
@pjtoussaint: sure, I agree
