### ISSUE TITLE
add new references

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#79]
https://www.sciencedirect.com/science/article/pii/S001094522030099X
and 
https://www.sciencedirect.com/science/article/pii/S1053811920303451

**Comment by pjtoussaint** [comment]
Zachlod D, Rüttgers B, Bludau S, Mohlberg H, Langner R, Zilles K, Amunts K (2020) **Four new cytoarchitectonic areas surrounding the primary and early auditory cortex in human brains.** *Cortex*, 128:1-21, https://doi.org/10.1016/j.cortex.2020.02.021

and

Royer J, Paquola C, Larivière S, Vos de Wael R, Tavakol S, Lowe AJ, Benkarim O, Evans AC, Bzdok D, Smallwood J, Frauscher B, Bernhardt BC (2020) **Myeloarchitecture gradients in the human insula: Histological underpinnings and association to intrinsic functional connectivity.** *NeuroImage*, 216:116859, https://doi.org/10.1016/j.neuroimage.2020.116859
