### ISSUE TITLE
Change Reference's style

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/3design.github.io#86]
We already discussed in any other issue, can't remember which one :/
Please unify the references layout. I propose the following, @pjtoussaint please correct me
- Abbreviate first names, e.g. Amunts K, Evans AC, ...
- Title bold
- Journal/Conf italic (not bold!)
- Order: <list of names> (<year>) **<title>**, _<journal>_, <metadata if given>, <link>

**Comment by pjtoussaint** [comment]
If we follow the examples that I gave from the beginning, we should be OK. My examples are very close to what  you would find in any proper scientific document.

The order should be: 
- comma separated authors (e.g. 'Amunts K, Evans AC, Anonymous A ')
- Year in parentheses (e.g. '(2020)')
- Title followed by period (Bold or not - I rather think it is irrelevant)
- Journal in italics (e.g. *J. Anat*, ) 
- issue volume(number if available): page-range, (e.g. '42(2):234-246, ')
- DOI:linking_to_journal

**Comment by SusanneWenzel** [comment]
E.g., please update
Katrin Amunts, Hartmut Mohlberg, Sebastian Bludau, Karl Zilles (2020) Julich-Brain: A 3D probabilistic atlas of the human brain’s cytoarchitecture. 
--
Amunts K, Mohlberg H, Bludau S, Zilles K (2020) **Julich-Brain: A 3D probabilistic atlas of the human brain’s cytoarchitecture**. Science, 369(6506):988-992, DOI: 10.1126/science.abb4588 

####
Wagstyl K, Larocque S, Cucurull G, Lepage C, Cohen JP, Bludau S, Palomero-Gallagher N, Lewis LB, Funck T, Spitzer H, Dickscheid T, Fletcher PC, Romero A, Zilles K, Amunts K, Bengio Y, Evans AC (2020) BigBrain 3D atlas of cortical layers: Cortical and laminar thickness gradients diverge in sensory and motor cortices
---
Wagstyl K, Larocque S, Cucurull G, Lepage C, Cohen JP, Bludau S, Palomero-Gallagher N, Lewis LB, Funck T, Spitzer H, Dickscheid T, Fletcher PC, Romero A, Zilles K, Amunts K, Bengio Y, Evans AC (2020) **BigBrain 3D atlas of cortical layers: Cortical and laminar thickness gradients diverge in sensory and motor cortices**. _PlosBiology_. DOI: 10.1038/s41467-020-17051-5

####
Seidlitz, Jakob & Nadig, Ajay & Liu, Siyuan & Bethlehem, Richard A.I. & Vértes, Petra & Morgan, Sarah & Váša, František & Romero-García, Rafael & Lalonde, François & Clasen, Liv & Blumenthal, Jonathan & Paquola, Casey & Bernhardt, Boris & Adler-Wagstyl, Konrad & Polioudakis, Damon & Torre-Ubieta, Luis & Geschwind, Daniel & Han, Joan & Lee, Nancy & Raznahan, Armin. (2020) Transcriptomic and cellular decoding of regional brain vulnerability to neurogenetic disorders. Nature Communications. 11. 10.1038/s41467-020-17051-5.
--
Seidlitz J, Nadig A, Liu S, Bethlehem RAI, Vértes PE, Morgan SE, Váša F, Romero-Garcia F, Lalonde FM, Clasen LS, Blumenthal JD, Paquola C, Bernhardt B, Wagstyl K, Polioudakis D, de la Torre-Ubieta L, Geschwind DH, Han JC, Lee NR, Murphy DG, Bullmore ET, Raznahan A (2020) **Transcriptomic and cellular decoding of regional brain vulnerability to neurogenetic disorders**. _Nature Communications_, 11(3358), DOI: 10.1038/s41467-020-17051-5
--->link broken, new: https://www.nature.com/articles/s41467-020-17051-5
---> btw, we have that entry twice

####
DeKraker J, Lau JC, Ferko KM, Khan AR, Kohler S (2019) Hippocampal subfields revealed through unfolding and unsupervised clustering of laminar and morphological features in 3D BigBrain. 
---
DeKraker J, Lau JC, Ferko KM, Khan AR, Kohler S (2019) **Hippocampal subfields revealed through unfolding and unsupervised clustering of laminar and morphological features in 3D BigBrain**. _NeuroImage_, 206(116328),DOI: 10.1016/j.neuroimage.2019.116328
