### ISSUE TITLE
Add -- Winter School 2021 Day 1: add speakers names and session titles

### ISSUE THREAD

**Issue by pjtoussaint** [3design/3design.github.io#92]
Day 1 - 01. Opening Address (Katrin Amunts)
Day 1 - 02. BigBrain anatomy for beginners (Nicola Palomero-Gallagher)
Day 1 - 03. Joint infrastructure for BigBrain (Petúr Helgi Einarsson)
Day 1 - 04. Short introduction to DataLad and Jülich activities (Morris Riedel)
Day 1 - 05. Hands-on: BigBrain data processing with CBRAIN and DataLad (Tristan Glatard)
Day 1 - 06. Hands-on: Processing BigBrain datasets with Boutiques (Valérie Hayot-Sasson)
Day 1 - 07. Hands-on: Contributing datasets to archives using DataLad (Tristan Glatard)
Day 1 - 08. BigBrain dataset and pipeline launching - NeuroHub overview (Bryan Caron)
Day 1 - 09. Hands-on: CBRAIN portal (Natacha Beck)
Day 1 - 10. BigBrain as part of the EBRAINS human brain atlas (Timo Dickscheid)
Day 1 - 11.  Introduction to Atelier3D (Louis Borgeat)
Day 1 - 12. Atelier3D: User perspective (Andrea Brandtstetter)
Day 1 - 13. Atelier3D: Use case and current developments (Mona Omidyeganeh)
Day 1 - 14. Wrap-up day 1 (Timo Dickscheid)

**Comment by SusanneWenzel** [comment]
I'm fine with having shorter videos, as long as it is clear to what session it belongs. On the other hand, to match the program, it would make sense to have one video per session/topic. I mean the visitor can decide to make a break or to jump to another part by itself. But, I don't mind, leave it up to you.
I'm not sure if it makes sense to have very long video names. May it happen that on small displays just the first part is visible? For that I'd go for shorter names and details in the description. 
Is it useful to have HIBALL in the name just for the google index?

**Comment by 3design** [comment]
I have applied these names to day 1 videos. Will need descriptions

https://www.youtube.com/playlist?list=PLGWf8gkjzAziEJFcH1dLVebKvGBXtcdT_

**Comment by SusanneWenzel** [comment]
In case you'll add an abstract for the playlist:

In February 2021 we held the first Winter School of the Helmholtz International BigBrain Analytics and Learning Laboratory (HIBALL). The courses offered introductions and practical hands-on sessions regarding BigBrain, related datasets and tools: IT-Infrastructure, image analysis, visualization and annotation. 
The BigBrain model has become an important tool for brain mapping, enabling studies and the integration of multimodal data into an anatomically realistic standard space at microscopic resolution. In a joint effort, researchers from McGill University in Montreal and the Forschungszentrum Jülich used 7404 digitized histological sections and developed the BigBrain as a high-resolution 3D model of the human brain (Amunts et al., Science 2013). HIBALL builds on this cross-continental cooperation and now aims to develop the next-generation high-resolution human brain models with the help of state of the art Machine Learning methods and high-performance computing infrastructures. With the teaching events of the BigBrain project, we reach out to the  thriving community of users and developers which has emerged around the BigBrain. We particularly invite young researchers to join the discussion and become part of the BigBrain community.

BigBrainProject https://bigbrainproject.org/ 
HIBALL https://bigbrainproject.org/hiball.html 
follow us on twitter @BigBrainProject



 
Title and description videos:


HIBALL WS21 – Opening

Katrin Amunts, Institute of Neuroscience and Medicine, Structural and functional organisation of the brain (INM-1), Forschungszentrum Jülich, Germany 
opening the first HIBALL Winter School on BigBrain data and tools, Feb 3, 2021

links: 
BigBrainProject https://bigbrainproject.org/ 
HIBALL https://bigbrainproject.org/hiball.html 

INM-1 https://www.fz-juelich.de/inm/inm-1/EN/Home/home_node.html
FZJ https://www.fz-juelich.de/portal/EN/Home/home_node.html
MCIN: https://mcin.ca/ 
McGill: https://www.mcgill.ca/ 

follow us on twitter @BigBrainProject


HIBALL WS21 - BigBrain anatomy for beginners

An introduction to the anatomy of the BigBrain 
HIBALL Winter School 2021 – BigBrain data and tools, Feb 3, 2021

Nicola Palomero-Gallagher, Institute of Neuroscience and Medicine, Structural and functional organisation of the brain (INM-1), Forschungszentrum Jülich, Germany

The goal of this course is to familiarize scientists with no, or only very little, knowledge about brain anatomy with major brain structures and their functions. You introduces the landmarks used by anatomists to navigate through the brain, and the functions they are involved in. Most importantly, you have a chance to search for these structures yourselves. By the end of the course you will not only be familiar with terms such as lobes, gyri, diencephalon, hippocampus or visual cortex, but you will also be able to find these structures in the BigBrain dataset.

links: 
the BigBrain at the ebrains atlas viewer https://atlases.ebrains.eu/viewer/?templateSelected=Big+Brain+%28Histology%29&parcellationSelected=Cytoarchitectonic+Maps+-+v2.4&cNavigation=0.0.0.-W000..2_ZG29.-ASCS.2-8jM2._aAY3..BSR0..6OMi.iVpO%7E.JPgu%7E..1jtG   

BigBrainProject https://bigbrainproject.org/ 
HIBALL https://bigbrainproject.org/hiball.html 

INM-1 https://www.fz-juelich.de/inm/inm-1/EN/Home/home_node.html
FZJ https://www.fz-juelich.de/portal/EN/Home/home_node.html

follow us on twitter @BigBrainProject



 
HIBALL WS21 – CBRAIN and DataLad

A tutorial on BigBrain data processing with CBRAIN and DataLad 
HIBALL Winter School 2021 – BigBrain data and tools, Feb 3, 2021

Petur Helgi Einarsson, Morris Riedel, Jülich Supercomputing Centre (JSC), Forschungszentrum Jülich, Germany, and School of Engineering and Natural Sciences of the University of Iceland
Tristan Glatard, Valérie Hayot-Sasson, Natacha Beck, Big Data Infrastructures for Neuroinformatics Lab, Department of Computer Science and Software Engineering (CSSE), Concordia University, Montreal, Canada

This tutorial provides an introduction to two tools that can be used to process and manage BigBrain-related data: CBRAIN and DataLad.
CBRAIN is a web portal that provides seamless access to high-performance computing clusters. DataLad is a data integration tool to keep track of distributed datasets. The tutorial covers the main functionalities of CBRAIN and DataLad, illustrate them on BigBrain data, and demonstrate their interaction.

links: 
jupyter notebook: https://colab.research.google.com/github/glatard/hws/blob/master/DataLad_Boutiques_tutorial.ipynb    
CONP: https://portal.conp.ca/ 

BigBrainProject https://bigbrainproject.org/ 
HIBALL https://bigbrainproject.org/hiball.html 

Big Data Infrastructures for Neuroinformatics https://big-data-lab-team.github.io/ 
CSSE: https://www.concordia.ca/ginacody/computer-science-software-eng.html?utm_source=redirect&utm_campaign=computer-science-software-engineering.html
Concordia: https://www.concordia.ca/ginacody/computer-science-software-eng.html?utm_source=redirect&utm_campaign=computer-science-software-engineering.html 
JSC: https://www.fz-juelich.de/ias/jsc/EN/Home/home_node.html 
FZJ https://www.fz-juelich.de/portal/EN/Home/home_node.html
UoI: https://english.hi.is/school_of_engineering_and_natural_sciences 

follow us on twitter @BigBrainProject




HIBALL WS21 – The EBRAINS human brain atlas

Tutorial on the BigBrain as a core part of the human brain atlas in the European EBRAINS platform 
HIBALL Winter School 2021 – BigBrain data and tools, Feb 3, 2021

Timo Dickscheid, Institute of Neuroscience and Medicine, Structural and functional organisation of the brain (INM-1), Forschungszentrum Jülich, Germany   

The EBRAINS multilevel human brain atlas integrates maps that capture different facets of human brain organization into a common framework. It is defined across multiple reference spaces, where BigBrain represents the micrometer level. The atlas links cytoarchitectonic areas with ultra-high resolution BigBrain data, complements them with maps of fibre architecture and functional organization, and links them to a growing set of multimodal data features associated to brain regions. EBRAINS atlas services are designed as an online framework that can be accessed interactively using an online viewer, as well as in a programmatic fashion through structured Python and http interfaces. This tutorial gives a tour of the recent status of EBRAINS atlas services, and discuss some future directions.

links: 
the BigBrain at the ebrains atlas viewer https://atlases.ebrains.eu/viewer/?templateSelected=Big+Brain+%28Histology%29&parcellationSelected=Cytoarchitectonic+Maps+-+v2.4&cNavigation=0.0.0.-W000..2_ZG29.-ASCS.2-8jM2._aAY3..BSR0..6OMi.iVpO%7E.JPgu%7E..1jtG   

BigBrainProject https://bigbrainproject.org/ 
HIBALL https://bigbrainproject.org/hiball.html 

INM-1 https://www.fz-juelich.de/inm/inm-1/EN/Home/home_node.html
FZJ https://www.fz-juelich.de/portal/EN/Home/home_node.html

follow us on twitter @BigBrainProject


HIBALL WS21 – Atelier3D

Atelier3D-MCIN Tutorial – A software suite for interactive visualization, annotation and mapping of the big brain 
HIBALL Winter School 2021 – BigBrain data and tools, Feb 3, 2021 

Louis Borgeat, Philippe Massicotte, National Research Council of Canada
Andrea Brandtstetter, , Institute of Neuroscience and Medicine, Structural and functional organisation of the brain (INM-1), Forschungszentrum Jülich, Germany
Mona Omidyeganeh, National Research Council of Canada and McGill Centre for Integrative Neuroscience, McGill University, Canada

This tutorial introduces the Atelier3D-MCIN software and utilities, and provide walk troughs of different annotations and mapping applications for the big brain. Atelier3D is a Windows and Linux-based software platform that provides powerful processing and visualization tools for the analysis of very large volume and surface datasets, and this version has been specifically adapted to support 3D annotation, segmentation and 3D surface extraction in the big brain in support of different use cases in McGill and Juelich. The tutorial covers installation and basic use of the software for local or remote visualization, and then focus on one or more specific scenarios of interest to the community, in collaboration with actual users of A3D. New and advanced features are also discussed, including interoperability with other tools and video production.

links: 
BigBrainProject https://bigbrainproject.org/ 
HIBALL https://bigbrainproject.org/hiball.html 

NRC: https://nrc.canada.ca/ 
MCIN: https://mcin.ca/ 
McGill: https://www.mcgill.ca/ 
INM-1 https://www.fz-juelich.de/inm/inm-1/EN/Home/home_node.html
FZJ https://www.fz-juelich.de/portal/EN/Home/home_node.html 

follow us on twitter @BigBrainProject

**Comment by 3design** [comment]
will need descriptions for 

Day 1 - 06. Hands-on: Processing BigBrain datasets with Boutiques (Valérie Hayot-Sasson)
Day 1 - 07. Hands-on: Contributing datasets to archives using DataLad (Tristan Glatard)
Day 1 - 08. BigBrain dataset and pipeline launching - NeuroHub overview (Bryan Caron)
Day 1 - 09. Hands-on: CBRAIN portal (Natacha Beck)

unless they share the same description as one of the ones above

**Comment by SusanneWenzel** [comment]
Indeed, these are all continuations of 05...cbrain and can be labeled as such

**Comment by 3design** [comment]
perfect. All descriptions entered except for the wrap-ups

**Comment by SusanneWenzel** [comment]
Can you please add Mohammad Shahbaz Memon to the description of the cbrain tutorials
I.e.,for Day 1 - 03.* ... Day 1 - 07.* 
Petur Helgi Einarsson, Mohammad Shahbaz Memon, Morris Riedel, Jülich Supercomputing Centre (JSC), Forschungszentrum Jülich, Germany, and School of Engineering and Natural Sciences of the University of Iceland
instead of 
Petur Helgi Einarsson, Morris Riedel, Jülich Supercomputing Centre (JSC), Forschungszentrum Jülich, Germany, and School of Engineering and Natural Sciences of the University of Iceland
